apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "db"
  DB_USER: "django"
  CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: "db"
  POSTGRES_USER: "django"

