# Generated by Django 5.1.6 on 2025-02-22 14:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_taskstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='task_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True),
        ),
    ]
